export const SET_CLICKED_DAY = 'SET_CLICKED_DAY';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const EDIT_SCHEDULE = 'EDIT_SCHEDULE';
export const GET_SCHEDULES = 'GET_SCHEDULES';
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const SET_SCHEDULE_LOADING = 'SET_SCHEDULE_LOADING';
export const SET_EVENTS_SCHEDULES_ON_SELECTED_DAY =
	'SET_EVENTS_SCHEDULES_ON_SELECTED_DAY';
export const GET_EVENTS_BASED_ON_SELECTED_DAY =
	'GET_EVENTS_BASED_ON_SELECTED_DAY';
